source 'https://supermarket.chef.io'

cookbook 'java', git: 'https://github.com/CatCalZone/java.git', ref: 'extract-to-tmp'
cookbook 'eclipse', git: 'https://github.com/geocent-cookbooks/eclipse', ref: 'master'
cookbook 'wildfly', git: 'https://github.com/bdwyertech/chef-wildfly.git', ref: 'master'
cookbook 'mysql', git: 'https://github.com/chef-cookbooks/mysql.git', ref: 'master'

metadata
