name 'vm'
maintainer 'Ken Iseli'
maintainer_email 'ken.iseli@gmail.com'
license 'MIT'
description 'Installs/Configures a Java Developer VM'
version '0.1.0'

depends 'apt', '2.8.2'
depends 'java', '1.32.0'
depends 'maven', '1.3.0'
depends 'eclipse', '0.1.0'
depends 'wildfly', '0.3.1'
depends 'mysql', '6.0.16'
